# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_title', models.CharField(max_length=30)),
                ('req_description', models.TextField()),
                ('target_date', models.DateField()),
                ('req_priority', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_request.Client_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='create_request',
            name='pro_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_request.Product_Area'),
        ),
    ]
