# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_request',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
