# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_request', '0002_create_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_request',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Created', max_length=40),
        ),
    ]
